version: "3.7"

services:
  # Backend API
  smart-brain-api: 
    container_name: backend
    # image: node:10
    build: ./
    command: npm start
    working_dir: /usr/src/Facial-api
    environment:
      POSTGRES_URI: postgres://Sally:secret@postgres:5432/smart-brain-docker
      REDIS_URI:  redis://redis:6379
    links:
      - postgres
      - redis
    ports:
      - "3000:3000"
    #Confict With copy modules pre-installed
    # volumes:
    #   - ./:/usr/src/Facial-api
  # Postgres
  postgres:
    environment:
      POSTGRES_USER: Sally
      POSTGRES_PASSWORD: secret
      POSTGRES_DB: smart-brain-docker
      POSTGRES_HOST: postgres
    # Ya no necesitamos esato porq ue esta ejecutandce el docker en el archivo dento ed postges folder
    # image: postgres
    build: ./postgres
    ports:
      - "5432:5432"
  # Redis
  redis:
    image: redis
    ports:
      - "6379:6379"